trigger:
  branches:
    include:
    - master
  paths:
    include:
    - src/TaylorBot.Net

resources:
- repo: self

variables:
  DOCKER_BUILDKIT: 1

stages:
- template: ../build-test-publish-dotnet-docker.yml
  parameters:
    componentName: commands-discord
    dockerfilePath: '$(Build.SourcesDirectory)/src/TaylorBot.Net/Program.Commands.Discord/Dockerfile'
    dockerBuildContext: '$(Build.SourcesDirectory)/src/TaylorBot.Net'
